function handleLogin() {
    // ...
    const redirectUrl = "https://auto-tube-web-v2.vercel.app/"; // Update the redirect URL
    window.location.href = redirectUrl; // Redirect to the specified URL
    // ...
} 